### ISSUE TITLE
Installation Problem?

### ISSUE THREAD

**Issue by plotloss** [akeneo-labs/EnhancedConnectorBundle#11]
Advised to post this question here, rather than the Akeneo forums.

Installed the Enhanced Connector (as we’re very keen on the delta export functionality) and whilst the install appears to have gone fine, I’m not seeing any of the extended options when creating an export profile.

When selecting Spread>Export Profiles>Jobs I only get the following options:

Product Export in CSV (and that's as it was before the install of bundle and assets)
Category Export in CSV
Attribute Export in CSV
Attribute Option Export in CSV
Association Type Export in CSV
Group Export in CSV
Variant Group Export in CSV
Published Product Export in CSV

Nowhere do I see anything related to the enhanced connector and I can't see where I've gone wrong. Please could someone advise if I've overlooked something or there's a genuine issue here.

**Comment by damien-carcel** [comment]
Hi.

The most likely reason for this kind of problem is a misconfiguration of the bundle. Did you correctly add the line "$bundles[] = new Pim\Bundle\EnhancedConnectorBundle\PimEnhancedConnectorBundle();" in the AppKernel::registerBundles() method?

Regards,
Damien

**Comment by plotloss** [comment]
Yes, that line is present in AppKernel.php

**Comment by damien-carcel** [comment]
Can you paste here the entire method where you add this line. It could be misplaced.
Have you any errors when you open Akeno in debug mode? Not even in the debug bar?

**Comment by plotloss** [comment]
```
public function registerBundles()
{
    $bundles = array();

    if (in_array($this->getEnvironment(), array('dev', 'test', 'behat'))) {
        $bundles[] = new Symfony\Bundle\WebProfilerBundle\WebProfilerBundle();
        $bundles[] = new Sensio\Bundle\DistributionBundle\SensioDistributionBundle();
        $bundles[] = new Sensio\Bundle\GeneratorBundle\SensioGeneratorBundle();
    }
    $bundles[] = new Pim\Bundle\EnhancedConnectorBundle\PimEnhancedConnectorBundle();
    $bundles = array_merge(
        $bundles,
        $this->getSymfonyBundles(),
        $this->getOroDependencies(),
        $this->getOroBundles(),
        $this->getPimDependenciesBundles(),
        $this->getPimBundles()
    );

    return $bundles;
}
```

Apologies, I'm not sure how to run akeneo in debug mode so haven't seen that.

**Comment by damien-carcel** [comment]
From the look of the first line of this method, I'd say you are using Akeneo 1.2. Am I correct? The enhanced connector bundle only work with Akeneo 1.3 and the future 1.4 version.

Regards,
Damien

**Comment by plotloss** [comment]
No, we're using 1.3.4 according to the front end.

**Comment by plotloss** [comment]
Version: EE 1.3.4 Strawberry (CE 1.3.4 Hare Force)

**Comment by damien-carcel** [comment]
OK, in this case are you using pim-community-standard or dev? You should use in any case the first one, the second is only for development purpose.

Anyway, try to move the line just before the "return $bundles;" statement, reinstall assets and clear the cache, then restart your apache server, it can sometimes make a difference.

If it still not work, try to launch Akeneo in dev mode by adding "/app_dev.php/" after your URL. You could have to edit the app_dev.php file (in the web folder of Akeneo) to add your IP address if Akeneo is installed on a distant server, as the dev mode is intended for localhost.

Regards,
Damien

**Comment by plotloss** [comment]
OK Damien, I will try that now, thank you very much for your help so far.

**Comment by plotloss** [comment]
Slightly curious.

I've updated app_dev.php to remove the block which checks the origin (it's commented out) and I've done this in two app_dev.php files and then cleared the cache and restarted Apache yet I'm still getting the 'You are not allowed to access this file. Check app_dev.php for more information.' message

**Comment by damien-carcel** [comment]
Did you comment all the if block, not just the the line with the IP addresses?
You only need to do it in the root web/app_dev.php. Those in the vendor folder are not used.

Regards,
Damien

**Comment by plotloss** [comment]
Hi Damien,

I now appear to have resolved it. Took a manual cache clear and reinstall.

Thank you so much for your help.

**Comment by damien-carcel** [comment]
Glad to hear that.

Indeed, I forgot about that, some time a simple "app/console cache:clear" isn't enough, one need to completely erase the cache folder.

Regards,
Damien
