### ISSUE TITLE
Export failed on "Export products using enhanced product reader"

### ISSUE THREAD

**Issue by jcpla** [akeneo-labs/EnhancedConnectorBundle#17]
The export fail on  "Export products using enhanced product reader" 

> [2015-10-02 15:20:44] php.CRITICAL: Fatal Error: Call to protected method Pim\Component\Connector\Writer\File\FileExporter::copyFile() from context 'Pim\Bundle\BaseConnectorBundle\Writer\File\CsvProductWriter' {"type":1,"file":"/akeneo/www/vendor/akeneo/pim-community-dev/src/Pim/Bundle/BaseConnectorBundle/Writer/File/CsvProductWriter.php","line":66,"level":6143,"stack":[]} []

I'm using PIM community 1.4.1

**Comment by damien-carcel** [comment]
Hello.

I'm sorry, but I cannot reproduce this bug on my environment. Can you try to update to the last version (1.4.3) of the PIM and try again?
What settings are you using for the export?
What data are you using (the demo data, or your own data)?

Regards,
Damien

**Comment by jcpla** [comment]
Hello Damien,

Having the lastest version may have correct the problem. I didn't dig a lot to find where the problem where.
Anyway it's ok now.

Thanks
JC
