### ISSUE TITLE
export issue with images

### ISSUE THREAD

**Issue by akkermanronald** [akeneo-labs/EnhancedConnectorBundle#20]
See screenshot. We are using 1.4.3 and MySQL storage, with demo data.

<img width="535" alt="schermafdruk 2015-10-11 18 31 30" src="https://cloud.githubusercontent.com/assets/15016164/10417737/6ef830b6-7046-11e5-8933-3c96829f9ccb.png">

**Comment by damien-carcel** [comment]
Hello.

This looks like a misconfiguration in your installation. Can you check that the picture indead exists?
Do you correctly configuration Apache user regarding read/write rights on you PIM install? It could be that Apache have no right to access the file.

Also, could you copy/past the content of the export log?

Regards,
Damien

**Comment by akkermanronald** [comment]
Thanks for your prompt reply. I suggest to test first by adding a new item and new picture to this instance. The issue is probably caused by the demo data not being 100% compatible with fresh 1.4 ? Do we perhaps need to carry out the media migration script even on a fresh install that was not upgraded? 

Regards
Ronald

**Comment by damien-carcel** [comment]
Hello.

Indeed, if you have done a migration from Akeneo 1.3 to 1.4, it could be the origin of the problem.
Could you try to run a standard product export, to see if the problem also happen (if it does, it's a problem with the PIM and the migration, not from the connector).

Regards,
Damien
