### ISSUE TITLE
export fails

### ISSUE THREAD

**Issue by akkermanronald** [akeneo-labs/EnhancedConnectorBundle#24]
Our export keeps failing after 15.000-17.000 items. Akeneo 1.4.4 running on very substantial hardware resources and optimised MySQL. We have 96.000 SKU to export. 

We have tried with and without filters on completness, modified date, etc.

**Comment by akkermanronald** [comment]
Additional information, the quick export also fails at 18.000, same failure message.

<img width="1075" alt="schermafdruk 2015-10-21 12 42 55" src="https://cloud.githubusercontent.com/assets/15016164/10634321/456aa780-77f1-11e5-86fb-639013407ec3.png">

**Comment by damien-carcel** [comment]
Hi.

If you can reproduce the problem with the quick export, then the problem does not come from the EnchancedConnectorBundle, but from the PIM itself. So this is not the right place to report it.

I recommand that you open a post on our forum here: http://www.akeneo.com/forums/

Regards,
Damien
