### ISSUE TITLE
There is no options in export profle creation

### ISSUE THREAD

**Issue by ewallteam** [akeneo-labs/EnhancedConnectorBundle#25]
Dear @damien-carcel ,

I have installed your EnhancedConnectorBundle in my Akeneo application but I did not got any changes in export profile section. And there is no options to create  the EnhancedConnector's Profile in Export Profile create section. See the below link.

https://drive.google.com/file/d/0B8aStV7rYyB6YVVtSkFHSXp4Yms/view?usp=drivesdk

Please help me to export the data from akeneo.

Thanks.

**Comment by damien-carcel** [comment]
Hello ewallteam.

Did you properly add "new Pim\Bundle\EnhancedConnectorBundle\PimEnhancedConnectorBundle();" in you AppKernel.php?
If you do, try to completely remove your application cache and clean it again:
    `rm -rf app/cache/* && app/console cache:clear --env=prod`
then restart apache. It could do the difference.

What's more, what version of Akeneo are you using?

Regards,
Damien

**Comment by ewallteam** [comment]
Hi @damien-carcel 
Thanks for your replyl, I have used Akeneo 1.3.28 Moreover we have already done, all the things you have suggested except the server restart. So we will do restart the apache and come back to you. 

Thannks,
Ewall Team.

**Comment by ewallteam** [comment]
Thanks @damien-carcel,
Now its working fine. Thanks for your support. I will close this issue..:)
