### ISSUE TITLE
How to do the store base migration from Magento to Akeneo?

### ISSUE THREAD

**Issue by ewallteam** [akeneo-labs/EnhancedConnectorBundle#32]
Hi All,

I have imported more than 10000 products from Magento to Akeneo by using this bundle. But now I have confused about the store base (Multi store) migration in Akeneo. Can anyone help me to do the same?

Thanks,
Ewall Team.

**Comment by damien-carcel** [comment]
Hi.

I think you're mixing the bundle with the native functionality of Akeneo. The Enhanced connector bundle does not provide any imports, only exports. The product import from Magento to Akeneo you are referring to has probably been realized with the native CSV product import.

Concerning the multi-store aspect, the standard way to do it on Akeneo is to use channels (one Akeneo channel corresponding to one Magento store).
However, this is more an Akeneo generic question than one related to this bundle. I suggests you take a look on Akeneo forums, where similar questions have already been raised, and eventually ask your question again there.

Regards,
Damien

**Comment by ewallteam** [comment]
Thanks for your suggestion @damien-carcel , I will check :-)
