### ISSUE TITLE
EnhancedConnector is slower 3 times than DnDMagentoConnector

### ISSUE THREAD

**Issue by manh-nguyen** [akeneo-labs/EnhancedConnectorBundle#33]
Hi guys,

Today we have some performance tests with Enhanced Connector and comparing to DnDMagentoConnector there are the information and result:
- Number of products in DB: 12000 products 
- Number of products in Default family: 4180 products 
- Family: Default (145 attributes)
- Tested on the same server
- MongoDB 
- DnDMagentoConnector on Akeneo 1.3
- EnhancedConnector on Akeneo 1.4
1. DnDMagentoConnector
   START: 2015-11-23 9:06:14 AM
   END:     2015-11-23 9:14:34 AM
   => 08:20
2. EnhancedConnector
   START: 2015-11-23 9:26:05 AM
   END:     2015-11-23 10:06:28 AM
   => 30:23

So EnhancedConnector is slower than DnDMagentoConnector 3.6 times.

Please check it and make it faster as I think It's really hard to accept this result comparing to DnDMagentoConnector.

Regards,
Manh - Balance Internet

**Comment by damien-carcel** [comment]
Hello Manh.

First, what are you exporting with the connectors? Only products, or is it a script that run a complete set of all exports (attributes, options, families and products) ?

Second, it is very strange that your test work at all, as you said that your install is in MongoDB and that the DnD Magento connector bundle does not support MongoDB. It will exports your catalog structure (attributes, options, families) but not your products, as it will not find them.
Did you realize a custom MongoDB product reader to make it work?

Regards,
Damien

**Comment by manh-nguyen** [comment]
Hi @damien-carcel ,

First, I'm taking care about Enhanced Connector product export only.
Second, DnD Magento Connector doesn't support MongoDB > Yes, we created another MongoDB reader based on DnD Magento Connector product reader to make it working with MongoDB.

Cheers,
Manh

**Comment by damien-carcel** [comment]
Thanks for your answer.

Then I will try to check it on my machine as soon as I can, comparing the two connectors with both Akeneo 1.3 and 1.4.
By the way, feel free to test your reader with the Enhanced connector processor and writer. It is possible it come from them, and not from the Reader part.
Also, remember that the DnD Magento connector bundle is open-source, so don't hesitate to make a pull request with your MongoDB reader if you want to.
We will also be very interested to see it and understand where the performance difference come from, and so improve our connector.

Regards,
Damien

**Comment by damien-carcel** [comment]
(sorry for the "close" action, wrong click on my side…)

**Comment by manh-nguyen** [comment]
Hi @damien-carcel ,

Please have a look at my dnd-mongodb-reader!

You can download the dnd-mongodb-reader.tar.gz from this link https://drive.google.com/file/d/0B2qFk6oF65ZNYVBRT2hXR05jTlE/view?usp=sharing 

Please don't forget to add this line to [YourConnector]Bundle/DependencyInjection/[YourConnector]Extension.php

{quote}
        $storageConfig = sprintf('storage_driver/%s.yml', $this->getStorageDriver($container));
        if (file_exists(**DIR**.'/../Resources/config/'.$storageConfig)) {
            $loader->load($storageConfig);
        }
{quote}

Cheers,
Manh
