### ISSUE TITLE
Installation doesn't work -_-' (Ubuntu 14.04, Akeneo 1.4)

### ISSUE THREAD

**Issue by kvancappel** [akeneo-labs/EnhancedConnectorBundle#35]
Hi,

  I follow this instructions > https://github.com/akeneo-labs/EnhancedConnectorBundle/

  Everything look to have been good.

php composer.phar require akeneo-labs/pim-enhanced-connector:~1.0 > OK
vi app/AppKernel.php > OK
php app/console cache:clear --env=prod > OK
php app/console pim:install:assets --env=prod > OK

  But, after installation, I've got a problem, I don't see anything more in "System > Configuration". I don't see "Catalog" and so I can't access to PimGento configuration.

  Could you help me please ?

  Thank you

  PS : my Akeneo version is 1.4.

**Comment by damien-carcel** [comment]
Hi.

So, everything seems good. There is indeed nothing new in "System → Configuration", and it is perfectly normal, that's not how the Enhanced connector work. If you go now in "Spread → Export profiles", then create a new export profile. You will then see some new export profiles available under the new section "Enhanced connector".

The export to Magento is in two part: an export in CSV from Akeneo (read the Enhanced connector documentation [here](https://github.com/akeneo-labs/EnhancedConnectorBundle/#use-of-the-enhanced-connector-bundle-with-pimgento)), then an import of these files into Mangento thanks to the PimGento module (you can find the related documentation [here](https://github.com/Agence-DnD/PIMGento#how-it-works)).

Regards,
Damien

**Comment by kvancappel** [comment]
Hi,

  thank you for your answer. Everything is OK.

  I've vot a last question, will PimGento be available with Magento 2.0 please ?

  Thank you again, Pimgento looks to be a very good connector ;-))

  Kévin

**Comment by damien-carcel** [comment]
Hi.

I cannot answer to that question, as Akeneo is not involved in PimGento development, only in the Enhanced connector. You should ask it directly to DnD, as they are the ones who develop PimGento.

Regards,
Damien.
