### ISSUE TITLE
https://api.github.com/repos/akeneo/pim-community-dev" file could not be downloaded

### ISSUE THREAD

**Issue by ramdama** [akeneo-labs/EnhancedConnectorBundle#39]
When I run the following command
php composer.phar require akeneo-labs/pim-enhanced-connector:~1.0
I am getting network address error

 [Composer\Downloader\TransportException]
  The "https://api.github.com/repos/akeneo/pim-community-dev" file could not be downloaded: php_network_getaddresses: getaddrinfo failed: Temporary failure in name r
  esolution
  failed to open stream: php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution

Need solution

**Comment by damien-carcel** [comment]
Hi.

It looks like a connection problem to GitHub. You should just try again, and if the error persist, try with another internet connection/computer.

Regards,
Damien

**Comment by fitn** [comment]
Hi,

I close this issue as it seems a connection problem to GitHub.

Regards,
