### ISSUE TITLE
Auto sync between Akeneo and Magento

### ISSUE THREAD

**Issue by ewallteam** [akeneo-labs/EnhancedConnectorBundle#50]
Hi,

We need to sync the changes between Akeneo and magento automatically, can you guys please help us to do the same? Moreover we have contacted Akeneo team regarding the same and they said that "the Enhanced Magento Connector + PIMgento is enough to make it work".

**Comment by fitn** [comment]
Hi @ewallteam

Could you tell me who has been contacted in Akeneo team please?

Regards,

**Comment by ewallteam** [comment]
Hi fitn,

The contact person name is Irina Périon, Akeneo Sales Coordinator. Its not a direct contact from our side and its from our end client side.

Kindly let me know the possibility to update the Magento products automatically whenever we add/update the product from Akeneo using the Enhanced Connector Bundle and Pimgento.

**Comment by gaurav-malhotra** [comment]
Need help related to this issue.. 
see commented posted on akeneo forum at the below path
http://www.akeneo.com/forums/topic/magento/#post-6790

Thanks in anticipation
Gaurav

**Comment by ewallteam** [comment]
Hi,

Is there any update on the possibility of auto sync the products between Akeneo and Magento?

**Comment by gaurav-malhotra** [comment]
Yes, Get the enhance connector bundle installed on the Akeneo side and pimgento on magento. For auto synch, you need to set up the export job + scp as crons on the akeneo server and enable cron for product's under pimgento's configuration.Also ensure that your magento cron.sh and cron.php are also set up in crontab.

follow below links for more details. Hope it helps..
http://docs.akeneo.com/master/cookbook/import_export/automate-import-exports.html
https://github.com/Agence-DnD/PIMGento

**Comment by fitn** [comment]
Thank you @gaurav-malhotra :)

I close the question. You can reopen it if something is not clear!

**Comment by Vanitha-Ramkumar** [comment]
Hi,

I'm using pim community standard edition  (1.7) for Akeneo. I couldn't install the Enhanced connector bundle. It throws an error.
I gone through a forums, it mentioned as Enhanced Connector bundle is applicable for pim community dev.

Is it true ?

Please advise.
