### ISSUE TITLE
Not enough job's

### ISSUE THREAD

**Issue by VasyaChernets** [akeneo-labs/EnhancedConnectorBundle#55]
Hello dear Akeneo Labs , i don't understand why when i try to export data with akeneo to the pimgento i see so little jobs?
![screenshot from 2016-02-24 11-43-27](https://cloud.githubusercontent.com/assets/15193807/13281585/54e315b2-daed-11e5-97fe-db15b4b1bb64.png)

Do I made a mistake when i install'ed "EnhancedConnectorBundle"?

**Comment by fitn** [comment]
Here is the answer if someone has the same question: http://www.akeneo.com/forums/topic/not-enough-jobs/#post-6881

Regards,
