### ISSUE TITLE
Exporting reference data in attribute options

### ISSUE THREAD

**Issue by buttash** [akeneo-labs/EnhancedConnectorBundle#58]
In #49 I raised the issue of exporting reference data values within the attribution option export.  In that thread it was said that:

> About reference datas, they are exported like options today. It needs custom export on PIM side for each reference data as we can't know the fields and format needed.

I have run a normal export and cannot see the reference data values.  Did I mis-understand the comment or am I doing something wrong?

Thanks
Martin

**Comment by fitn** [comment]
Hi @buttash 

I did a products export with reference datas. You can see the reference datas linked to product values like that (color and fabrics columns): 
![image](https://cloud.githubusercontent.com/assets/2131005/14251228/475116d8-fa82-11e5-96d6-ec760778c95d.png)

But the export of your reference datas itself should be a dedicated ones (one export = one reference data). It is not linked to the attribute options as the columns could be everything in the reference datas.
The attribute options CSV export is a native and dedicated export. There is no native CSV export for reference datas. We would provide one in the https://github.com/akeneo-labs/CustomEntityBundle but I don't know when it will be done.

I don't advice you to add reference datas in the native attribute options export as it will override these datas are heterogenous and you will need to override the default behavior.

I hope my answer is more clear now :)

Regards,

**Comment by jmleroux** [comment]
Do not hesitate to reopen if needed.
