### ISSUE TITLE
Installed Bundle no job is available in export profile only default akeneo jobs are there

### ISSUE THREAD

**Issue by emaan-zepcom** [akeneo-labs/EnhancedConnectorBundle#71]
I have installed the bundle then cleared cache and install asset there is no error but in export profile there are only default akeneo jobs are available no other job is there.
![exportprofile](https://cloud.githubusercontent.com/assets/14107589/14453689/b4d7afea-00af-11e6-8cce-300eb94d8019.PNG)

**Comment by jmleroux** [comment]
Hello @emaan-zepcom ,

First, did you register the EnhancedConnector bundle in your [AppKernel.php](https://github.com/akeneo-labs/EnhancedConnectorBundle#installation)

Then, you should create a profile from a job before trying to filter. To create a new profile from an enhanced job, you just have to click on the big green button and choose one job from the enhanced connector. ;)

Regards,
JM

**Comment by emaan-zepcom** [comment]
i have followed all steps including register clear cache and install assets.

Once i create Profile then in job drop down there is no job from the enhanced connector only default akeneo jobs are there.

**Comment by jmleroux** [comment]
Could we have any access to your sources: github, ssh, etc.

Feel free to join me in private if the access should not be public: jean-marie.leroux@akeneo.com
Or on the slack User Group as i know you're already a member.
