### ISSUE TITLE
Export products updated since the last execution of this job

### ISSUE THREAD

**Issue by mstaroste** [akeneo-labs/EnhancedConnectorBundle#73]
Hello,

is it possible that the standard "Product import in CSV" job sets a update date?
Because when I import data to update any product the "Export products updated since the last execution of this job" don't recognize it.

**Comment by mstaroste** [comment]
Any ideas?

**Comment by jmleroux** [comment]
Hello @mstaroste ,

Ths date should exist. It may be a bug.
Which version of PIM and Enhanced connector do you use ?

**Comment by jmleroux** [comment]
BTW, you can check the date in your databaseby adapting this query to your need: https://github.com/akeneo-labs/EnhancedConnectorBundle/blob/master/Reader/ProductReader.php#L495

**Comment by mstaroste** [comment]
Hello @jmleroux,

thanks for your assist.
I'm using since today Akeneo version:1.5.2 and the latest Enhanced connector.

I tested again and it's the same problem. When a import was running the Enhanced connector don't recognize it and nothing will exported.

**Comment by jmleroux** [comment]
Hello @mstaroste ,

Firstly, sorry for the delay.
I tried to reproduce your problem but didn't succeed.

I traced the query with XDEBUG and it looks good for the date filter. The generated query is something like this:

```
SELECT o.id FROM Pim\Component\Catalog\Model\Product o INDEX BY o.id 
LEFT JOIN o.categories filterCategory574bfb71f3a4e 
LEFT JOIN PimCatalogBundle:Channel filterCompleteness574bfbcfd5b9bChannel WITH filterCompleteness574bfbcfd5b9bChannel.code = :cScopeCode 
LEFT JOIN Pim\Component\Catalog\Model\Completeness filterCompleteness574bfbcfd5b9b WITH filterCompleteness574bfbcfd5b9b.product = o.id AND filterCompleteness574bfbcfd5b9b.channel = filterCompleteness574bfbcfd5b9bChannel.id 
WHERE filterCategory574bfb71f3a4e.id IN(:filterCatIds574bfb71f3a88) 
AND o.updated >= '2016-05-30 08:35:23' 
AND o.enabled = true 
AND filterCompleteness574bfbcfd5b9b.ratio = 100 
GROUP BY o.id
```

where we can see the date filter.

Could you try to debug your query to see what it looks like ?

You can do it launching the command with XDEBUG with a breakpoint on this line https://github.com/akeneo-labs/EnhancedConnectorBundle/blob/master/Reader/ProductReader.php#L371

To launch the job, just run `app/console akeneo:batch:job <job_code>` in your favorite debugging tool (i use PhpStorm).

**Comment by jmleroux** [comment]
hi @mstaroste ,

any news about this issue ?

**Comment by jmleroux** [comment]
Closed without activity.
