### ISSUE TITLE
Installation issue on Bitnami app instance

### ISSUE THREAD

**Issue by beespaulding** [akeneo-labs/EnhancedConnectorBundle#74]
Hello,
I've been trying to install the enhanced connector bundle to a bitnami app instance on a remote server.  I've followed the installation directions and once I clear the cache and dump my assets I can no longer connect to my server app.  I get this message:

**The adnd.bitnamiapp.com page isn’t working**
 adnd.bitnamiapp.com is currently unable to handle this request.
 500

All other steps seem to work just fine (after tweaking the memory limits).  Any help or suggestions would be greatly appreciated.

**Comment by jmleroux** [comment]
hello @beespaulding ,
it is a bit difficult to help you without more information.
Did you check the logs: `app/logs/prod.log` and maybe `/var/log/apache2/error.log`  ?

Also, if you can access it in dev mode, you could have more information.

**Comment by beespaulding** [comment]
Hey @jmleroux 
To be clear, I'm a bit of a newbie with this stuff.  I've done a complete re-install of the apps and I've been trying to find errors in my approach.  I've been following instructions from the bitnami website, with no success. (https://docs.bitnami.com/google/apps/akeneo/#howtoinstallmegentoconnectorbundle?)

After increasing the memory size and running the "php composer require ..." I'm now seeing the same result.

Here is the current error log from /opt/bitnami/apache2/logs:

> [Mon Apr 25 13:54:08.880690 2016] [ssl:warn] [pid 1708:tid 140103847798592] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
> [Mon Apr 25 13:54:09.001268 2016] [ssl:warn] [pid 1709:tid 140103847798592] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
> [Mon Apr 25 13:54:09.001792 2016] [lbmethod_heartbeat:notice] [pid 1709:tid 140103847798592] AH02282: No slotmem from mod_heartmonitor
> [Mon Apr 25 13:54:09.059701 2016] [mpm_event:notice] [pid 1709:tid 140103847798592] AH00489: Apache/2.4.20 (Unix) OpenSSL/1.0.2g mod_wsgi/3.5 Python/2.7.11 configured -- resuming normal operations
> [Mon Apr 25 13:54:09.059736 2016] [core:notice] [pid 1709:tid 140103847798592] AH00094: Command line: '/opt/bitnami/apache2/bin/httpd.bin -f /opt/bitnami/apache2/conf/httpd.conf'
> [Mon Apr 25 13:54:14.141051 2016] [mpm_event:notice] [pid 1709:tid 140103847798592] AH00491: caught SIGTERM, shutting down
> [Mon Apr 25 13:54:17.055581 2016] [ssl:warn] [pid 2378:tid 140538775631680] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
> [Mon Apr 25 13:54:17.169241 2016] [ssl:warn] [pid 2379:tid 140538775631680] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
> [Mon Apr 25 13:54:17.169341 2016] [lbmethod_heartbeat:notice] [pid 2379:tid 140538775631680] AH02282: No slotmem from mod_heartmonitor
> [Mon Apr 25 13:54:17.213900 2016] [mpm_event:notice] [pid 2379:tid 140538775631680] AH00489: Apache/2.4.20 (Unix) OpenSSL/1.0.2g mod_wsgi/3.5 Python/2.7.11 configured -- resuming normal operations
> [Mon Apr 25 13:54:17.213937 2016] [core:notice] [pid 2379:tid 140538775631680] AH00094: Command line: '/opt/bitnami/apache2/bin/httpd.bin -f /opt/bitnami/apache2/conf/httpd.conf'
> [Mon Apr 25 13:57:58.590267 2016] [mpm_event:notice] [pid 2379:tid 140538775631680] AH00491: caught SIGTERM, shutting down
> [Mon Apr 25 13:58:00.935104 2016] [ssl:warn] [pid 3522:tid 140693577643840] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
> [Mon Apr 25 13:58:01.063705 2016] [ssl:warn] [pid 3523:tid 140693577643840] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
> [Mon Apr 25 13:58:01.063822 2016] [lbmethod_heartbeat:notice] [pid 3523:tid 140693577643840] AH02282: No slotmem from mod_heartmonitor
> [Mon Apr 25 13:58:01.093668 2016] [mpm_event:notice] [pid 3523:tid 140693577643840] AH00489: Apache/2.4.20 (Unix) OpenSSL/1.0.2g mod_wsgi/3.5 Python/2.7.11 configured -- resuming normal operations
> [Mon Apr 25 13:58:01.093705 2016] [core:notice] [pid 3523:tid 140693577643840] AH00094: Command line: '/opt/bitnami/apache2/bin/httpd.bin -f /opt/bitnami/apache2/conf/httpd.conf'
> [Mon Apr 25 13:59:47.930292 2016] [mpm_event:notice] [pid 3523:tid 140693577643840] AH00491: caught SIGTERM, shutting down
> [Mon Apr 25 13:59:50.267673 2016] [ssl:warn] [pid 4213:tid 139854842230592] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
> [Mon Apr 25 13:59:50.402182 2016] [ssl:warn] [pid 4214:tid 139854842230592] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
> [Mon Apr 25 13:59:50.402288 2016] [lbmethod_heartbeat:notice] [pid 4214:tid 139854842230592] AH02282: No slotmem from mod_heartmonitor
> [Mon Apr 25 13:59:50.430382 2016] [mpm_event:notice] [pid 4214:tid 139854842230592] AH00489: Apache/2.4.20 (Unix) OpenSSL/1.0.2g mod_wsgi/3.5 Python/2.7.11 configured -- resuming normal operations
> [Mon Apr 25 13:59:50.430424 2016] [core:notice] [pid 4214:tid 139854842230592] AH00094: Command line: '/opt/bitnami/apache2/bin/httpd.bin -f /opt/bitnami/apache2/conf/httpd.conf'
> [Mon Apr 25 14:19:32.979271 2016] [proxy_fcgi:error] [pid 4221:tid 139854444709632] [client 67.231.56.25:41388] AH01071: Got error 'PHP message: PHP Parse error:  syntax error, unexpected ')' in /opt/bitnami/apps/akeneo/htdocs/web/app_dev.php on line 15\n'
> [Mon Apr 25 14:19:45.131501 2016] [proxy_fcgi:error] [pid 4222:tid 139854343997184] [client 67.231.56.25:21033] AH01071: Got error 'PHP message: PHP Parse error:  syntax error, unexpected ')' in /opt/bitnami/apps/akeneo/htdocs/web/app_dev.php on line 15\n'
> [Mon Apr 25 14:19:46.191776 2016] [proxy_fcgi:error] [pid 4219:tid 139854461495040] [client 67.231.56.25:18489] AH01071: Got error 'PHP message: PHP Parse error:  syntax error, unexpected ')' in /opt/bitnami/apps/akeneo/htdocs/web/app_dev.php on line 15\n'
> [Mon Apr 25 14:21:04.956677 2016] [proxy_fcgi:error] [pid 4569:tid 139854117394176] [client 67.231.56.25:58931] AH01071: Got error 'PHP message: PHP Parse error:  syntax error, unexpected '.56' (T_DNUMBER), expecting ']' in /opt/bitnami/apps/akeneo/htdocs/web/app_dev.php on line 12\n'
> [Mon Apr 25 14:21:06.582944 2016] [proxy_fcgi:error] [pid 4487:tid 139854453102336] [client 67.231.56.25:36668] AH01071: Got error 'PHP message: PHP Parse error:  syntax error, unexpected '.56' (T_DNUMBER), expecting ']' in /opt/bitnami/apps/akeneo/htdocs/web/app_dev.php on line 12\n'
> [Mon Apr 25 14:21:07.213103 2016] [proxy_fcgi:error] [pid 4221:tid 139854419531520] [client 67.231.56.25:30932] AH01071: Got error 'PHP message: PHP Parse error:  syntax error, unexpected '.56' (T_DNUMBER), expecting ']' in /opt/bitnami/apps/akeneo/htdocs/web/app_dev.php on line 12\n'
> [Mon Apr 25 14:21:07.597280 2016] [proxy_fcgi:error] [pid 4219:tid 139854453102336] [client 67.231.56.25:26130] AH01071: Got error 'PHP message: PHP Parse error:  syntax error, unexpected '.56' (T_DNUMBER), expecting ']' in /opt/bitnami/apps/akeneo/htdocs/web/app_dev.php on line 12\n'
> [Mon Apr 25 14:34:00.591065 2016] [pagespeed:warn] [pid 4569:tid 139854343997184] [mod_pagespeed 1.9.32.14-0 @4569] Failed to read cache clean timestamp /opt/bitnami/apache2/var/cache/mod_pagespeed/!clean!time!.  Doing an extra cache clean to be safe.
> [Mon Apr 25 15:33:52.512738 2016] [proxy_fcgi:error] [pid 4222:tid 139854192928512] [client 67.231.56.25:39382] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Failed to write cache file "/opt/bitnami/apps/akeneo/htdocs/app/cache/prod/classes.php".' in /opt/bitnami/apps/akeneo/htdocs/vendor/symfony/symfony/src/Symfony/Component/ClassLoader/ClassCollectionLoader.php:239\nStack trace:\n#0 /opt/bitnami/apps/akeneo/htdocs/vendor/symfony/symfony/src/Symfony/Component/ClassLoader/ClassCollectionLoader.php(122): Symfony\Component\ClassLoader\ClassCollectionLoader::writeCacheFile('/opt/bitnami/ap...', '<?php \nnamespac...')\n#1 /opt/bitnami/apps/akeneo/htdocs/app/bootstrap.php.cache(2557): Symfony\Component\ClassLoader\ClassCollectionLoader::load(Array, '/opt/bitnami/ap...', 'classes', false, false, '.php')\n#2 /opt/bitnami/apps/akeneo/htdocs/app/bootstrap.php.cache(2392): Symfony\Component\HttpKernel\Kernel->doLoadClassCache('classes', '.php')\n#3 /opt/bitnami/apps/akeneo/htdocs/app/bootstrap.php.cache(2426): Symfony\Component\HttpKernel\Kernel->boot()\n#4 /opt/bitnami/apps/akeneo/htdocs/web/a...\n', referer: http://showroom.bitnamiapp.com/akeneo/
> [Mon Apr 25 15:57:49.399973 2016] [proxy_fcgi:error] [pid 4569:tid 139854150964992] [client 67.231.56.25:18952] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Failed to write cache file "/opt/bitnami/apps/akeneo/htdocs/app/cache/prod/classes.php".' in /opt/bitnami/apps/akeneo/htdocs/vendor/symfony/symfony/src/Symfony/Component/ClassLoader/ClassCollectionLoader.php:239\nStack trace:\n#0 /opt/bitnami/apps/akeneo/htdocs/vendor/symfony/symfony/src/Symfony/Component/ClassLoader/ClassCollectionLoader.php(122): Symfony\Component\ClassLoader\ClassCollectionLoader::writeCacheFile('/opt/bitnami/ap...', '<?php \nnamespac...')\n#1 /opt/bitnami/apps/akeneo/htdocs/app/bootstrap.php.cache(2557): Symfony\Component\ClassLoader\ClassCollectionLoader::load(Array, '/opt/bitnami/ap...', 'classes', false, false, '.php')\n#2 /opt/bitnami/apps/akeneo/htdocs/app/bootstrap.php.cache(2392): Symfony\Component\HttpKernel\Kernel->doLoadClassCache('classes', '.php')\n#3 /opt/bitnami/apps/akeneo/htdocs/app/bootstrap.php.cache(2426): Symfony\Component\HttpKernel\Kernel->boot()\n#4 /opt/bitnami/apps/akeneo/htdocs/web/a...\n', referer: http://showroom.bitnamiapp.com/akeneo/
> [Mon Apr 25 15:57:53.376606 2016] [proxy_fcgi:error] [pid 4487:tid 139854436316928] [client 67.231.56.25:9470] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Failed to write cache file "/opt/bitnami/apps/akeneo/htdocs/app/cache/prod/classes.php".' in /opt/bitnami/apps/akeneo/htdocs/vendor/symfony/symfony/src/Symfony/Component/ClassLoader/ClassCollectionLoader.php:239\nStack trace:\n#0 /opt/bitnami/apps/akeneo/htdocs/vendor/symfony/symfony/src/Symfony/Component/ClassLoader/ClassCollectionLoader.php(122): Symfony\Component\ClassLoader\ClassCollectionLoader::writeCacheFile('/opt/bitnami/ap...', '<?php \nnamespac...')\n#1 /opt/bitnami/apps/akeneo/htdocs/app/bootstrap.php.cache(2557): Symfony\Component\ClassLoader\ClassCollectionLoader::load(Array, '/opt/bitnami/ap...', 'classes', false, false, '.php')\n#2 /opt/bitnami/apps/akeneo/htdocs/app/bootstrap.php.cache(2392): Symfony\Component\HttpKernel\Kernel->doLoadClassCache('classes', '.php')\n#3 /opt/bitnami/apps/akeneo/htdocs/app/bootstrap.php.cache(2426): Symfony\Component\HttpKernel\Kernel->boot()\n#4 /opt/bitnami/apps/akeneo/htdocs/web/a...\n'
> [Mon Apr 25 15:57:54.298650 2016] [proxy_fcgi:error] [pid 4569:tid 139854142572288] [client 67.231.56.25:48364] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Failed to write cache file "/opt/bitnami/apps/akeneo/htdocs/app/cache/prod/classes.php".' in /opt/bitnami/apps/akeneo/htdocs/vendor/symfony/symfony/src/Symfony/Component/ClassLoader/ClassCollectionLoader.php:239\nStack trace:\n#0 /opt/bitnami/apps/akeneo/htdocs/vendor/symfony/symfony/src/Symfony/Component/ClassLoader/ClassCollectionLoader.php(122): Symfony\Component\ClassLoader\ClassCollectionLoader::writeCacheFile('/opt/bitnami/ap...', '<?php \nnamespac...')\n#1 /opt/bitnami/apps/akeneo/htdocs/app/bootstrap.php.cache(2557): Symfony\Component\ClassLoader\ClassCollectionLoader::load(Array, '/opt/bitnami/ap...', 'classes', false, false, '.php')\n#2 /opt/bitnami/apps/akeneo/htdocs/app/bootstrap.php.cache(2392): Symfony\Component\HttpKernel\Kernel->doLoadClassCache('classes', '.php')\n#3 /opt/bitnami/apps/akeneo/htdocs/app/bootstrap.php.cache(2426): Symfony\Component\HttpKernel\Kernel->boot()\n#4 /opt/bitnami/apps/akeneo/htdocs/web/a...\n'
> [Mon Apr 25 15:57:54.763751 2016] [proxy_fcgi:error] [pid 4569:tid 139854134179584] [client 67.231.56.25:8175] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Failed to write cache file "/opt/bitnami/apps/akeneo/htdocs/app/cache/prod/classes.php".' in /opt/bitnami/apps/akeneo/htdocs/vendor/symfony/symfony/src/Symfony/Component/ClassLoader/ClassCollectionLoader.php:239\nStack trace:\n#0 /opt/bitnami/apps/akeneo/htdocs/vendor/symfony/symfony/src/Symfony/Component/ClassLoader/ClassCollectionLoader.php(122): Symfony\Component\ClassLoader\ClassCollectionLoader::writeCacheFile('/opt/bitnami/ap...', '<?php \nnamespac...')\n#1 /opt/bitnami/apps/akeneo/htdocs/app/bootstrap.php.cache(2557): Symfony\Component\ClassLoader\ClassCollectionLoader::load(Array, '/opt/bitnami/ap...', 'classes', false, false, '.php')\n#2 /opt/bitnami/apps/akeneo/htdocs/app/bootstrap.php.cache(2392): Symfony\Component\HttpKernel\Kernel->doLoadClassCache('classes', '.php')\n#3 /opt/bitnami/apps/akeneo/htdocs/app/bootstrap.php.cache(2426): Symfony\Component\HttpKernel\Kernel->boot()\n#4 /opt/bitnami/apps/akeneo/htdocs/web/a...\n'
> [Mon Apr 25 16:00:54.560294 2016] [proxy_fcgi:error] [pid 4569:tid 139854125786880] [client 67.231.56.25:10952] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Failed to write cache file "/opt/bitnami/apps/akeneo/htdocs/app/cache/prod/classes.php".' in /opt/bitnami/apps/akeneo/htdocs/vendor/symfony/symfony/src/Symfony/Component/ClassLoader/ClassCollectionLoader.php:239\nStack trace:\n#0 /opt/bitnami/apps/akeneo/htdocs/vendor/symfony/symfony/src/Symfony/Component/ClassLoader/ClassCollectionLoader.php(122): Symfony\Component\ClassLoader\ClassCollectionLoader::writeCacheFile('/opt/bitnami/ap...', '<?php \nnamespac...')\n#1 /opt/bitnami/apps/akeneo/htdocs/app/bootstrap.php.cache(2557): Symfony\Component\ClassLoader\ClassCollectionLoader::load(Array, '/opt/bitnami/ap...', 'classes', false, false, '.php')\n#2 /opt/bitnami/apps/akeneo/htdocs/app/bootstrap.php.cache(2392): Symfony\Component\HttpKernel\Kernel->doLoadClassCache('classes', '.php')\n#3 /opt/bitnami/apps/akeneo/htdocs/app/bootstrap.php.cache(2426): Symfony\Component\HttpKernel\Kernel->boot()\n#4 /opt/bitnami/apps/akeneo/htdocs/web/a...\n'
> [Mon Apr 25 16:00:55.181689 2016] [proxy_fcgi:error] [pid 4221:tid 139854260070144] [client 67.231.56.25:11460] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Failed to write cache file "/opt/bitnami/apps/akeneo/htdocs/app/cache/prod/classes.php".' in /opt/bitnami/apps/akeneo/htdocs/vendor/symfony/symfony/src/Symfony/Component/ClassLoader/ClassCollectionLoader.php:239\nStack trace:\n#0 /opt/bitnami/apps/akeneo/htdocs/vendor/symfony/symfony/src/Symfony/Component/ClassLoader/ClassCollectionLoader.php(122): Symfony\Component\ClassLoader\ClassCollectionLoader::writeCacheFile('/opt/bitnami/ap...', '<?php \nnamespac...')\n#1 /opt/bitnami/apps/akeneo/htdocs/app/bootstrap.php.cache(2557): Symfony\Component\ClassLoader\ClassCollectionLoader::load(Array, '/opt/bitnami/ap...', 'classes', false, false, '.php')\n#2 /opt/bitnami/apps/akeneo/htdocs/app/bootstrap.php.cache(2392): Symfony\Component\HttpKernel\Kernel->doLoadClassCache('classes', '.php')\n#3 /opt/bitnami/apps/akeneo/htdocs/app/bootstrap.php.cache(2426): Symfony\Component\HttpKernel\Kernel->boot()\n#4 /opt/bitnami/apps/akeneo/htdocs/web/a...\n'
> [Mon Apr 25 16:00:55.708383 2016] [proxy_fcgi:error] [pid 4219:tid 139854150964992] [client 67.231.56.25:39175] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Failed to write cache file "/opt/bitnami/apps/akeneo/htdocs/app/cache/prod/classes.php".' in /opt/bitnami/apps/akeneo/htdocs/vendor/symfony/symfony/src/Symfony/Component/ClassLoader/ClassCollectionLoader.php:239\nStack trace:\n#0 /opt/bitnami/apps/akeneo/htdocs/vendor/symfony/symfony/src/Symfony/Component/ClassLoader/ClassCollectionLoader.php(122): Symfony\Component\ClassLoader\ClassCollectionLoader::writeCacheFile('/opt/bitnami/ap...', '<?php \nnamespac...')\n#1 /opt/bitnami/apps/akeneo/htdocs/app/bootstrap.php.cache(2557): Symfony\Component\ClassLoader\ClassCollectionLoader::load(Array, '/opt/bitnami/ap...', 'classes', false, false, '.php')\n#2 /opt/bitnami/apps/akeneo/htdocs/app/bootstrap.php.cache(2392): Symfony\Component\HttpKernel\Kernel->doLoadClassCache('classes', '.php')\n#3 /opt/bitnami/apps/akeneo/htdocs/app/bootstrap.php.cache(2426): Symfony\Component\HttpKernel\Kernel->boot()\n#4 /opt/bitnami/apps/akeneo/htdocs/web/a...\n'

After running:
**bitnami ip  [censored]:/opt/bitnami/apps/akeneo/htdocs$ sudo php composer.phar require akeneo/magento-connector-bundle:master-dev**
Warning: This development build of composer is over 60 days old. It is recommended to update it by running "composer.phar self-update" to get the latest version.
./composer.json has been updated
Loading composer repositories with package information                                                 Updating dependencies (including require-dev)         Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for akeneo/magento-connector-bundle master-dev -> satisfiable by akeneo/magento-connector-bundle[dev-master].
    - akeneo/magento-connector-bundle dev-master requires akeneo/pim-community-dev ~1.2@stable,<1.4 -> no matching package found.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://getcomposer.org/doc/04-schema.md#minimum-stability for more details.

Read https://getcomposer.org/doc/articles/troubleshooting.md for further common problems.

Installation failed, reverting ./composer.json to its original content.

So now i'm even more unsure of what the problem is.  I have tried following instructions from github and bitnami.  Both instructions are similar but a bit different. But both result in my instance breaking.

Thanks again for your help!

**Comment by beespaulding** [comment]
I also get the same 

>  The showroom.bitnamiapp.com page isn’t working
> showroom.bitnamiapp.com is currently unable to handle this request.
> 500

Message when trying to connect in dev mode.

**Comment by jmleroux** [comment]
```
67.231.56.25:39175] AH01071: Got error 'PHP message: PHP Fatal error: Uncaught exception 'RuntimeException' with message 'Failed to write cache file 
```

=> permission problem or no disk space left maybe

**Comment by beespaulding** [comment]
Interesting, I'm inclined to believe that it would have to be an issue with space/memory.  I believe I was running the commands as the root user (w/ 'sudo su') 
The only straightforward errors I've been encountering have to do with memory.  Even after trying to increase the allocated space via the php.ini and akeneo console files.  I've even set up swap space.  

I don't suppose there's any way to manually import these files?  I was able to get everything up and running on the Magento side no problem. 

I've increased my server size and space.  I'm going to take a crack at it again.  I'll let you know how it works out.

Thank you again for your advise.  I greatly appreciate it.

**Comment by beespaulding** [comment]
Quick follow up,
@jmleroux you were correct with the nature of the error message.  With Bitnami deployed apps it is critical to change these permissions after installing the enhanced connector

> If you are running Akeneo in a virtual machine or cloud image, or you installed Akeneo as root user you will need update the following permissions/ownership:
> sudo chmod -R 777 app/cache
> sudo chgrp -R daemon vendor

As soon as I had run those commands I was able to access my application again.  Now I'm just trying to figure out how to expose the updates now that they are installed...   =p

**Comment by jmleroux** [comment]
can we close then ?

**Comment by beespaulding** [comment]
Yes Sir!

Thank you!
