### ISSUE TITLE
doctrine/migrations error during install

### ISSUE THREAD

**Issue by tjuola** [akeneo-labs/EnhancedConnectorBundle#81]
I’m trying to create demo environment with Akeneo CE 1.5 and Magento 2.1 CE by using Pimgento.
I get this weird error message at the end of installation process:
ubuntu@ip-172-31-46-149:/var/www/html/pim-community-standard$ sudo php composer.phar require akeneo-labs/pim-enhanced-connector:~1.2
Running composer as root/super user is highly discouraged as packages, plugins and scripts cannot always be trusted
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

Problem 1
– akeneo/pim-community-dev v1.5.5 requires doctrine/migrations 1.0.0-alpha3@alpha -> satisfiable by doctrine/migrations[v1.0.0-alpha3].
– akeneo/pim-community-dev v1.5.5 requires doctrine/migrations 1.0.0-alpha3@alpha -> satisfiable by doctrine/migrations[v1.0.0-alpha3].
– Removal request for doctrine/migrations == 1.0.0.0-alpha3
– Installation request for akeneo/pim-community-dev (locked at v1.5.5) -> satisfiable by akeneo/pim-community-dev[v1.5.5].

Installation failed, reverting ./composer.json to its original content.
ubuntu@ip-172-31-46-149:/var/www/html/pim-community-standard$

**Comment by jmleroux** [comment]
hello @tjuola 

it seems related to this PR: https://github.com/akeneo-labs/EnhancedConnectorBundle/commit/320017257a0fc09cae75c1046bc0d1ee91f0e0a5

i'll see with @fitn and get back to you

Another thing, not related to your problem: you should not use `sudo` for `composer update` :wink: 

JM

**Comment by fitn** [comment]
Hi @tjuola 

Sorry for this late answer.

You have to add doctrine/migrations in your composer dependencies as it is not stable ;)
Let me know if it does not resolved your issue.

Regards,
