### ISSUE TITLE
Requirement Issue for ConnecterBundle version 1.4

### ISSUE THREAD

**Issue by LexKoomen** [akeneo-labs/EnhancedConnectorBundle#89]
php composer.phar require akeneo-labels/pim-enhanced-connector:~1.4

./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package akeneo-labels/pim-enhanced-connector could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.

Is 1.4 not in production yet for akeneo 1.7?

**Comment by jmleroux** [comment]
Hello @LexKoomen ,

you should use `akeneo-labs` and not `akeneo-labels` :wink: 

Regards,
JM
