### ISSUE TITLE
Issue in installing in Enhanced Connector Bundle in Akeneo 1.7

### ISSUE THREAD

**Issue by Vanitha-Ramkumar** [akeneo-labs/EnhancedConnectorBundle#93]
Hi,
I tried to install enhanced connector bundle in Akeneo 1.7 ununtu 16.04. But I received the below error. Please assist me to resolve thiss issue.

**sudo php composer.phar require akeneo-labs/pim-enhanced-connector:~1.4**

Do not run Composer as root/super user! See https://getcomposer.org/root for details
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - akeneo-labs/pim-enhanced-connector v1.4.1 requires akeneo/pim-community-dev 1.7.* -> no matching package found.
    - akeneo-labs/pim-enhanced-connector v1.4.0 requires akeneo/pim-community-dev 1.7.* -> no matching package found.
    - Installation request for akeneo-labs/pim-enhanced-connector ~1.4 -> satisfiable by akeneo-labs/pim-enhanced-connector[v1.4.0, v1.4.1].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, deleting ./composer.json.

**Comment by jmleroux** [comment]
Hello @Vanitha-Ramkumar ,

I don't understand why you have this composer error. The pim-community-dev is well registered in the composer.json : https://github.com/akeneo/pim-community-standard/blob/v1.7.6/composer.json#L22

Which PIM project are you using?
